Detect location of registers in signal context structures for Mac OS X 10.5 x86.
git-svn-id: svn://svn.code.sf.net/p/polyml/code/trunk/polyml@355 ae7d391e-3f74-4a2b-a0db-a8776840fd2a

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -26209,132 +26209,6 @@ _ACEOF
 
 
 fi
-{ echo "$as_me:$LINENO: checking for x86_thread_state32_t" >&5
-echo $ECHO_N "checking for x86_thread_state32_t... $ECHO_C" >&6; }
-if test "${ac_cv_type_x86_thread_state32_t+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include "signal.h"
-#include "ucontext.h"
-
-typedef x86_thread_state32_t ac__type_new_;
-int
-main ()
-{
-if ((ac__type_new_ *) 0)
-  return 0;
-if (sizeof (ac__type_new_))
-  return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_cv_type_x86_thread_state32_t=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_type_x86_thread_state32_t=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_type_x86_thread_state32_t" >&5
-echo "${ECHO_T}$ac_cv_type_x86_thread_state32_t" >&6; }
-if test $ac_cv_type_x86_thread_state32_t = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_X86_THREAD_STATE32_T 1
-_ACEOF
-
-
-fi
-{ echo "$as_me:$LINENO: checking for x86_thread_state64_t" >&5
-echo $ECHO_N "checking for x86_thread_state64_t... $ECHO_C" >&6; }
-if test "${ac_cv_type_x86_thread_state64_t+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  cat >conftest.$ac_ext <<_ACEOF
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include "signal.h"
-#include "ucontext.h"
-
-typedef x86_thread_state64_t ac__type_new_;
-int
-main ()
-{
-if ((ac__type_new_ *) 0)
-  return 0;
-if (sizeof (ac__type_new_))
-  return 0;
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext
-if { (ac_try="$ac_compile"
-case "(($ac_try" in
-  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
-  *) ac_try_echo=$ac_try;;
-esac
-eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
-  (eval "$ac_compile") 2>conftest.er1
-  ac_status=$?
-  grep -v '^ *+' conftest.er1 >conftest.err
-  rm -f conftest.er1
-  cat conftest.err >&5
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } && {
-	 test -z "$ac_c_werror_flag" ||
-	 test ! -s conftest.err
-       } && test -s conftest.$ac_objext; then
-  ac_cv_type_x86_thread_state64_t=yes
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-	ac_cv_type_x86_thread_state64_t=no
-fi
-
-rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
-fi
-{ echo "$as_me:$LINENO: result: $ac_cv_type_x86_thread_state64_t" >&5
-echo "${ECHO_T}$ac_cv_type_x86_thread_state64_t" >&6; }
-if test $ac_cv_type_x86_thread_state64_t = yes; then
-
-cat >>confdefs.h <<_ACEOF
-#define HAVE_X86_THREAD_STATE64_T 1
-_ACEOF
-
-
-fi
 
 { echo "$as_me:$LINENO: checking for struct sigcontext" >&5
 echo $ECHO_N "checking for struct sigcontext... $ECHO_C" >&6; }
@@ -30856,6 +30730,7 @@ done
 
 
 # Where are the registers?
+#Linux:
 { echo "$as_me:$LINENO: checking for mcontext_t.gregs" >&5
 echo $ECHO_N "checking for mcontext_t.gregs... $ECHO_C" >&6; }
 if test "${ac_cv_member_mcontext_t_gregs+set}" = set; then
@@ -31166,6 +31041,7 @@ _ACEOF
 
 fi
 
+#Mac OS X:
 { echo "$as_me:$LINENO: checking for struct mcontext.ss" >&5
 echo $ECHO_N "checking for struct mcontext.ss... $ECHO_C" >&6; }
 if test "${ac_cv_member_struct_mcontext_ss+set}" = set; then
@@ -31477,6 +31353,426 @@ if test $ac_cv_member_struct___darwin_mcontext___ss = yes; then
 
 cat >>confdefs.h <<_ACEOF
 #define HAVE_STRUCT___DARWIN_MCONTEXT___SS 1
+_ACEOF
+
+
+fi
+{ echo "$as_me:$LINENO: checking for struct __darwin_mcontext32.ss" >&5
+echo $ECHO_N "checking for struct __darwin_mcontext32.ss... $ECHO_C" >&6; }
+if test "${ac_cv_member_struct___darwin_mcontext32_ss+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext32 ac_aggr;
+if (ac_aggr.ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext32_ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext32 ac_aggr;
+if (sizeof ac_aggr.ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext32_ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_member_struct___darwin_mcontext32_ss=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_member_struct___darwin_mcontext32_ss" >&5
+echo "${ECHO_T}$ac_cv_member_struct___darwin_mcontext32_ss" >&6; }
+if test $ac_cv_member_struct___darwin_mcontext32_ss = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_STRUCT___DARWIN_MCONTEXT32_SS 1
+_ACEOF
+
+
+fi
+{ echo "$as_me:$LINENO: checking for struct __darwin_mcontext32.__ss" >&5
+echo $ECHO_N "checking for struct __darwin_mcontext32.__ss... $ECHO_C" >&6; }
+if test "${ac_cv_member_struct___darwin_mcontext32___ss+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext32 ac_aggr;
+if (ac_aggr.__ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext32___ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext32 ac_aggr;
+if (sizeof ac_aggr.__ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext32___ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_member_struct___darwin_mcontext32___ss=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_member_struct___darwin_mcontext32___ss" >&5
+echo "${ECHO_T}$ac_cv_member_struct___darwin_mcontext32___ss" >&6; }
+if test $ac_cv_member_struct___darwin_mcontext32___ss = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_STRUCT___DARWIN_MCONTEXT32___SS 1
+_ACEOF
+
+
+fi
+{ echo "$as_me:$LINENO: checking for struct __darwin_mcontext64.ss" >&5
+echo $ECHO_N "checking for struct __darwin_mcontext64.ss... $ECHO_C" >&6; }
+if test "${ac_cv_member_struct___darwin_mcontext64_ss+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext64 ac_aggr;
+if (ac_aggr.ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext64_ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext64 ac_aggr;
+if (sizeof ac_aggr.ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext64_ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_member_struct___darwin_mcontext64_ss=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_member_struct___darwin_mcontext64_ss" >&5
+echo "${ECHO_T}$ac_cv_member_struct___darwin_mcontext64_ss" >&6; }
+if test $ac_cv_member_struct___darwin_mcontext64_ss = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_STRUCT___DARWIN_MCONTEXT64_SS 1
+_ACEOF
+
+
+fi
+{ echo "$as_me:$LINENO: checking for struct __darwin_mcontext64.__ss" >&5
+echo $ECHO_N "checking for struct __darwin_mcontext64.__ss... $ECHO_C" >&6; }
+if test "${ac_cv_member_struct___darwin_mcontext64___ss+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext64 ac_aggr;
+if (ac_aggr.__ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext64___ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include "signal.h"
+#include "ucontext.h"
+
+int
+main ()
+{
+static struct __darwin_mcontext64 ac_aggr;
+if (sizeof ac_aggr.__ss)
+return 0;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_cv_member_struct___darwin_mcontext64___ss=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_member_struct___darwin_mcontext64___ss=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_member_struct___darwin_mcontext64___ss" >&5
+echo "${ECHO_T}$ac_cv_member_struct___darwin_mcontext64___ss" >&6; }
+if test $ac_cv_member_struct___darwin_mcontext64___ss = yes; then
+
+cat >>confdefs.h <<_ACEOF
+#define HAVE_STRUCT___DARWIN_MCONTEXT64___SS 1
 _ACEOF
 
 
